export const BEGIN_AJAX_CALL       = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR       = 'AJAX_CALL_ERROR';

export const LOAD_WRESTLERS_SUCCESS  = 'LOAD_WRESTLERS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS  = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_WRESTLER_SUCCESS = 'CREATE_WRESTLER_SUCCESS';
export const UPDATE_WRESTLER_SUCCESS = 'UPDATE_WRESTLER_SUCCESS';
